### ISSUE TITLE
Virtual notch for oscillator detune knob

### ISSUE THREAD

**Issue by oO** [MeeBlip/meeblip-triode#6]
I'm actually tempted to replace the pot for the detune parameters for one that has a hardware center detent. But for everyone else, having a virtual center implemented in software, where the values are shifted so it's easier to keep the oscillators in tune should you want too.

**Comment by jgrahame** [comment]
The detune knob already has a virtual center detent. If knob value is 125 - 128, we set detune to zero and lock oscillators. Because the detune amount is nonlinear (increases the detune amount as we move away from the center position), we have to be restrict the size of the center detent because we have limited knob resolution of only 256 values.
